name: Cloud Run Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and Push Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/de-jasm-globant .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/de-jasm-globant

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy de-jasm-globant \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/de-jasm-globant \
          --platform managed \
          --region [REGION] # Reemplaza [REGION] con la región donde deseas desplegar la aplicación.
